"use client";
import { create } from 'zustand';

const useLanguageStore = create((set, get) => ({
  lang: typeof window !== 'undefined' ? (localStorage.getItem('lang') || 'en') : 'en',
  isRTL: typeof window !== 'undefined' ? ((localStorage.getItem('lang') || 'en') === 'ar') : false,

  setLang: (lang) => {
    localStorage.setItem('lang', lang);
    set({ lang, isRTL: lang === 'ar' });
  },

  toggleLang: () => {
    const newLang = get().lang === 'en' ? 'ar' : 'en';
    localStorage.setItem('lang', newLang);
    set({ lang: newLang, isRTL: newLang === 'ar' });
  },

  t: (key) => {
    const lang = get().lang;
    const keys = key.split('.');
    let value = translations[lang];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  },
}));

const translations = {
  en: {
    // Navbar
    nav: {
      home: 'Home',
      dashboard: 'Dashboard',
      upload: 'Upload',
      logout: 'Logout',
      signIn: 'Sign In',
      signUp: 'Sign Up',
    },
    // Common
    common: {
      loading: 'Loading...',
      error: 'An error occurred',
      success: 'Success',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
    },
    // Badges / Gamification
    badges: {
      beginner: 'Beginner',
      active: 'Active Learner',
      diligent: 'Diligent Student',
      scholar: 'Distinguished Scholar',
      genius: 'Genius',
    },
    // Home
    home: {
      title: 'EduVision',
      titleAI: 'AI',
      subtitle: 'An intelligent learning platform powered by AI to summarize videos and generate questions',
      welcomeBack: 'Welcome back,',
      authSubtitle: 'Ready to compress more knowledge today?',
      goToDashboard: 'Go to Dashboard',
      uploadPDF: 'Upload PDF',
      getStarted: 'Get Started Free',
      uploadVideo: 'Upload Video',
      letsUpload: "Let's Upload 🚀",
      files: 'Files',
      videos: 'Videos',
      docs: 'Docs',
      image: 'Image',
      video: 'Video',
      url: 'Video URL',
      smartSummaries: 'Smart Summaries',
      smartSummariesDesc: 'Automatic video summarization using AI',
      interactiveQuestions: 'Interactive Questions',
      interactiveQuestionsDesc: 'Auto-generated questions to test comprehension',
      summarizedClips: 'Mind Map',
      summarizedClipsDesc: 'Extract core ideas and key points from any long video instantly',
      recentVideos: 'Recent Videos',
      views: 'views',
    },
    // Login
    login: {
      title: 'Sign In',
      email: 'Email',
      password: 'Password',
      submit: 'Sign In',
      submitting: 'Signing in...',
      noAccount: "Don't have an account?",
      createAccount: 'Create Account',
    },
    // Register
    register: {
      title: 'Create Account',
      username: 'Username',
      fullName: 'Full Name',
      email: 'Email',
      password: 'Password',
      submit: 'Create Account',
      submitting: 'Creating account...',
      hasAccount: 'Already have an account?',
      signIn: 'Sign In',
    },
    // Dashboard
    dashboard: {
      welcome: 'Welcome back,',
      subtitle: 'Track your learning progress, manage content, and review your quiz scores.',
      uploadNew: 'Upload New Content',
      averageAccuracy: 'Average Accuracy',
      quizzesTaken: 'Quizzes Taken',
      uploadedVideos: 'Uploaded Content',
      activeSince: 'Active Since',
      yourLibrary: 'Your Library',
      noVideos: "You haven't uploaded any content yet",
      startUploading: 'Start Uploading',
      studyVideo: 'Study Video',
      recentQuizzes: 'Recent Quizzes',
      attempt: 'Attempt',
      score: 'Score',
      noQuizzes: 'No quizzes taken yet.',
      studyToTest: 'Study a file to test your knowledge.',
      browseVideos: 'Browse content →',
      aiReady: 'AI Ready',
      deleteConfirm: 'Are you sure you want to delete this video?',
      searchPlaceholder: 'Search by title...',
      filterAll: 'All',
      filterVideos: 'Videos',
      filterFiles: 'Files',
      noResults: 'No results found',
      points: 'Points',
      studyPDF: 'Study PDF',
      aiRecommendations: '🧠 AI Study Plan',
      generatePlan: 'Generate AI Study Plan',
      generating: 'AI is analyzing your performance...',
      overallGrade: 'Overall Grade',
      priority: 'Priority',
      noQuizzesForPlan: 'Take at least one quiz to get AI recommendations.',
      motivationalMsg: 'AI Coach Says',
    },
    // Upload
    upload: {
      title: 'Upload Content',
      documents: 'Files',
      videos: 'Videos',
      photo: 'Photo',
      presentation: 'PowerPoint',
      image: 'Image',
      uploadVideo: 'Upload Video',
      videoUrl: 'Video URL',
      selectFile: 'Select Video File',
      selectImage: 'Select Image',
      selectPPTX: 'Select PowerPoint',
      clickToSelect: 'Click to select a video',
      clickToSelectDoc: 'Click to select a document',
      clickToSelectPDF: 'Click to select a PDF',
      clickToSelectImage: 'Click to select an image',
      clickToSelectPPTX: 'Click to select a PowerPoint',
      maxSize: 'Max size: 500MB',
      selectPDF: 'Select PDF File',
      maxSizePDF: 'Max size: 50MB',
      maxSizeImage: 'Max size: 20MB',
      maxSizePPTX: 'Max size: 50MB',
      analyzePDF: 'Analyze PDF',
      analyzeImage: 'Analyze Image',
      analyzePPTX: 'Analyze PowerPoint',
      analyzeVideo: 'Analyze Video',
      analyzeDocuments: 'Analyze Documents',
      removeFile: 'Remove File',
      urlLabel: 'Video URL',
      urlPlaceholder: 'https://youtube.com/watch?v=...',
      ytAutoFetch: 'Title will be auto-fetched from YouTube',
      videoTitle: 'Video Title',
      imageTitle: 'Image Title',
      docTitle: 'Document Title',
      docTitlePlaceholder: 'Enter document title',
      imageTitlePlaceholder: 'Enter image title',
      videoTitlePlaceholder: 'Enter video title',
      titleOptional: '(optional — auto-fetched)',
      titleRequired: '*',
      titlePlaceholder: 'Enter video title',
      titleAutoPlaceholder: '',
      description: 'Description (optional)',
      descPlaceholder: 'Add a description for the video...',
      optionalPrompt: 'AI Instructions (optional)',
      promptPlaceholder: 'Tell AI what to focus on... e.g. "Summarize chapter 3 only" or "Solve the math problems"',
      customPrompt: 'Custom AI Instructions',
      category: 'Category',
      categories: {
        science: 'Science',
        technology: 'Technology',
        mathematics: 'Mathematics',
        history: 'History',
        language: 'Languages',
        arts: 'Arts',
        business: 'Business',
        other: 'Other',
      },
      uploading: 'Uploading...',
      processing: 'Processing...',
      savingAnalysis: 'Saving video & starting AI analysis...',
      analyzeYT: 'Analyze YouTube Video',
      uploadBtn: 'Analyze Video',
      preview: 'Video Preview',
      docPreview: 'Docs Preview',
      pdfPreview: 'PDF Preview',
      imagePreview: 'Image Preview',
      pptxPreview: 'Presentation Preview',
      previewTitle: 'Title',
      previewAutoFetch: '(Auto-fetch from YouTube)',
      untitledVideo: 'Untitled Video',
      type: 'Type',
      categoryLabel: 'Category',
      aiFeatures: '🤖 AI Features',
      aiFeaturesDesc: 'After upload, AI will automatically generate: Summary, Mind Map, and Quiz Questions',
      aiImageDesc: 'AI will analyze the image: detect text, solve math problems, explain diagrams, and more',
      selectFilePreview: 'Select a file to see preview',
      enterUrlPreview: 'Enter a URL to see preview',
      errorFile: 'Please select a file',
      errorUrl: 'Please enter a video URL',
      errorTitle: 'Please enter a title',
    },
    // Video Detail
    video: {
      views: 'views',
      aiAnalyzing: 'AI is analyzing this video...',
      waitingProcess: 'Waiting to start processing...',
      generatingContent: 'Generating summary, key points, and quiz questions...',
      summary: 'Summary',
      summaryNA: '⚠️ The video is too short or doesn\'t contain enough content for summarization.',
      summaryTip: '💡',
      tipTitle: 'Tip:',
      tipDesc: 'For a detailed summary, upload a video that:',
      tipPoint1: 'Is at least one minute long',
      tipPoint2: 'Contains educational content or clear explanations',
      tipPoint3: 'Has good audio quality',
      keyPoints: 'Mind Map',
      keyPointsNA: '📌 Mind Map is not available for very short videos.',
      description: 'Description',
      quiz: 'Interactive Quiz',
      quizCompleted: 'Quiz Completed!',
      accuracy: 'Accuracy',
      yourAnswer: 'Your Answer:',
      correctAnswer: 'Correct Answer:',
      explanation: 'Explanation:',
      answerAll: 'Please answer all questions before submitting.',
      submitAnswers: 'Submit Answers',
      submitting: 'Submitting...',
      processingStatus: 'Processing Status',
      completed: 'Completed ✅',
      processingLabel: 'Processing... 🔄',
      failed: 'Failed ❌',
      pending: 'Pending ⏳',
      retryAnalysis: 'Retry AI Analysis',
      retrying: 'Retrying...',
      videoInfo: 'Video Info',
      docInfo: 'Document Info',
      categoryLabel: 'Category',
      unspecified: 'Unspecified',
      duration: 'Duration',
      pageCount: 'Pages',
      uploaded: 'Uploaded',
      aiModel: 'AI Model',
      notFound: 'Video not found',
      mindMap: 'Visual Mind Map',
      tapToFlip: 'Tap to flip card',
      flashcards: 'Smart Flashcards',
      exportPDF: 'Install PDF',
      studyMode: 'Study Mode',
      testMode: 'Quiz',
      pages: 'pages',
      mindMapTitle: 'Interactive Mind Map',
    },
  },
  ar: {
    // Common
    common: {
      loading: 'جاري التحميل...',
      error: 'حدث خطأ',
      success: 'تم بنجاح',
      save: 'حفظ',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
    },
    // Badges / Gamification
    badges: {
      beginner: 'مبتدئ',
      active: 'متعلم نشط',
      diligent: 'طالب مجتهد',
      scholar: 'باحث متميز',
      genius: 'عبقري',
    },
    // Navbar
    nav: {
      home: 'الرئيسية',
      dashboard: 'لوحة التحكم',
      upload: 'رفع فيديو',
      logout: 'تسجيل خروج',
      signIn: 'تسجيل دخول',
      signUp: 'إنشاء حساب',
    },
    // Home
    home: {
      title: 'EduVision',
      titleAI: 'AI',
      subtitle: 'منصة تعليمية ذكية تستخدم الذكاء الاصطناعي لتلخيص الفيديوهات وتوليد الأسئلة',
      welcomeBack: 'أهلاً بك مجدداً يا',
      authSubtitle: 'هل أنت مستعد لاكتساب المزيد من المعرفة اليوم؟',
      goToDashboard: 'الذهاب للوحة التحكم',
      uploadPDF: 'رفع PDF',
      getStarted: 'ابدأ مجاناً',
      uploadVideo: 'رفع فيديو',
      letsUpload: 'يلا نرفع 🚀',
      files: 'ملفات',
      videos: 'فيديوهات',
      docs: 'مستندات',
      image: 'صورة',
      video: 'فيديو',
      url: 'رابط فيديو',
      smartSummaries: 'ملخصات ذكية',
      smartSummariesDesc: 'تلخيص تلقائي للفيديو باستخدام الذكاء الاصطناعي',
      interactiveQuestions: 'أسئلة تفاعلية',
      interactiveQuestionsDesc: 'أسئلة تلقائية لاختبار مدى الفهم',
      summarizedClips: 'الخريطة الذهنية',
      summarizedClipsDesc: 'استخراج الأفكار الأساسية والنقاط الرئيسية من أي فيديو طويل في ثوانٍ',
      recentVideos: 'أحدث الفيديوهات',
      views: 'مشاهدة',
    },
    // Login
    login: {
      title: 'تسجيل الدخول',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      submit: 'تسجيل الدخول',
      submitting: 'جاري الدخول...',
      noAccount: 'ليس لديك حساب؟',
      createAccount: 'إنشاء حساب',
    },
    // Register
    register: {
      title: 'إنشاء حساب جديد',
      username: 'اسم المستخدم',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      submit: 'إنشاء حساب',
      submitting: 'جاري إنشاء الحساب...',
      hasAccount: 'لديك حساب بالفعل؟',
      signIn: 'تسجيل الدخول',
    },
    // Dashboard
    dashboard: {
      welcome: 'أهلاً بعودتك،',
      subtitle: 'جاهز لرحلة تعلم جديدة؟ تابع إنجازك واستكشف المزيد.',
      uploadNew: 'رفع محتوى جديد',
      averageAccuracy: 'متوسط الدقة',
      quizzesTaken: 'اختبارات مكتملة',
      uploadedVideos: 'محتوى مرفوع',
      activeSince: 'عضو منذ',
      yourLibrary: 'مكتبتك',
      noVideos: 'مكتبتك فارغة! هل أنت مستعد للبدء؟ 🚀',
      startUploading: 'ارفع أول محتوى لك',
      studyVideo: 'ادرس الفيديو',
      recentQuizzes: 'آخر الاختبارات',
      attempt: 'المحاولة',
      score: 'النتيجة',
      noQuizzes: 'لم تحل أي اختبار بعد.',
      studyToTest: 'ادرس فيديو لاختبار معرفتك.',
      browseVideos: 'تصفح الفيديوهات ←',
      aiReady: 'جاهز للدراسة',
      deleteConfirm: 'هل أنت متأكد من حذف هذا الفيديو؟',
      searchPlaceholder: 'ابحث بالعنوان...',
      filterAll: 'الكل',
      filterVideos: 'فيديوهات',
      filterFiles: 'ملفات',
      noResults: 'لا توجد نتائج',
      points: 'نقطة',
      studyPDF: 'ادرس الـ PDF',
      aiRecommendations: '🧠 خطة دراسية ذكية',
      generatePlan: 'توليد خطة دراسية بالذكاء الاصطناعي',
      generating: 'الذكاء الاصطناعي يحلل أداءك...',
      overallGrade: 'التقييم العام',
      priority: 'الأولوية',
      noQuizzesForPlan: 'أكمل اختباراً واحداً على الأقل للحصول على توصيات.',
      motivationalMsg: 'المستشار الذكي يقول',
    },
    // Upload
    upload: {
      title: 'رفع محتوى جديد',
      documents: 'ملفات',
      videos: 'فيديوهات',
      photo: 'صورة',
      presentation: 'بوربوينت',
      image: 'صورة',
      uploadVideo: 'رفع فيديو',
      videoUrl: 'رابط فيديو',
      selectFile: 'اختر ملف الفيديو',
      selectImage: 'اختر صورة',
      selectPPTX: 'اختر عرض بوربوينت',
      clickToSelect: 'اضغط لاختيار فيديو',
      clickToSelectDoc: 'اضغط لاختيار مستند',
      clickToSelectPDF: 'اضغط لاختيار ملف PDF',
      clickToSelectImage: 'اضغط لاختيار صورة',
      clickToSelectPPTX: 'اضغط لاختيار عرض بوربوينت',
      maxSize: 'الحد الأقصى: 500 ميجابايت',
      selectPDF: 'اختر ملف PDF',
      maxSizePDF: 'الحد الأقصى: 50 ميجابايت',
      maxSizeImage: 'الحد الأقصى: 20 ميجابايت',
      maxSizePPTX: 'الحد الأقصى: 50 ميجابايت',
      analyzePDF: 'تحليل PDF',
      analyzeImage: 'تحليل الصورة',
      analyzePPTX: 'تحليل البوربوينت',
      analyzeVideo: 'تحليل الفيديو',
      analyzeDocuments: 'تحليل المستندات',
      removeFile: 'إزالة الملف',
      urlLabel: 'رابط الفيديو',
      urlPlaceholder: 'https://youtube.com/watch?v=...',
      ytAutoFetch: 'سيتم جلب العنوان تلقائياً من يوتيوب',
      videoTitle: 'عنوان الفيديو',
      imageTitle: 'عنوان الصورة',
      docTitle: 'عنوان المستند',
      docTitlePlaceholder: 'أدخل عنوان المستند',
      imageTitlePlaceholder: 'أدخل عنوان الصورة',
      videoTitlePlaceholder: 'أدخل عنوان الفيديو',
      titleOptional: '(اختياري — يُجلب تلقائياً)',
      titleRequired: '*',
      titlePlaceholder: 'أدخل عنوان الفيديو',
      titleAutoPlaceholder: '',
      description: 'الوصف (اختياري)',
      descPlaceholder: 'أضف وصفاً للفيديو...',
      optionalPrompt: 'تعليمات للذكاء الاصطناعي (اختياري)',
      promptPlaceholder: 'قل للذكاء الاصطناعي ركز على إيه... مثلاً "لخصلي الفصل التالت بس" أو "حل المسائل الرياضية"',
      customPrompt: 'تعليمات مخصصة للـ AI',
      category: 'التصنيف',
      categories: {
        science: 'علوم',
        technology: 'تكنولوجيا',
        mathematics: 'رياضيات',
        history: 'تاريخ',
        language: 'لغات',
        arts: 'فنون',
        business: 'أعمال',
        other: 'أخرى',
      },
      uploading: 'جاري الرفع...',
      processing: 'عقلنا الاصطناعي يحلل المحتوى الآن... ⏳',
      savingAnalysis: 'نجهز لك سحر الذكاء الاصطناعي... ✨',
      analyzeYT: 'تحليل فيديو يوتيوب',
      uploadBtn: 'تحليل الفيديو',
      preview: 'Video Preview',
      docPreview: 'Docs Preview',
      pdfPreview: 'معاينة PDF',
      imagePreview: 'Image Preview',
      pptxPreview: 'معاينة العرض التقديمي',
      previewTitle: 'العنوان',
      previewAutoFetch: '(جلب تلقائي من يوتيوب)',
      untitledVideo: 'بدون عنوان',
      type: 'النوع',
      categoryLabel: 'التصنيف',
      aiFeatures: '🤖 ميزات الذكاء الاصطناعي',
      aiFeaturesDesc: 'بعد الرفع، سيقوم الذكاء الاصطناعي تلقائياً بإنشاء: ملخص، خريطة ذهنية، وأسئلة اختبارية',
      aiImageDesc: 'الذكاء الاصطناعي هيحلل الصورة: يقرأ النص، يحل المسائل، يشرح الرسومات، وأكتر',
      selectFilePreview: 'اختر ملفاً لرؤية المعاينة',
      enterUrlPreview: 'أدخل رابطاً لرؤية المعاينة',
      errorFile: 'من فضلك اختر ملف',
      errorUrl: 'من فضلك أدخل رابط الفيديو',
      errorTitle: 'من فضلك أدخل العنوان',
    },
    // Video Detail
    video: {
      views: 'مشاهدة',
      aiAnalyzing: 'عقلنا الاصطناعي يقرأ الفيديو الآن، جهّز قهوتك! ☕',
      waitingProcess: 'في طابور العمليات الذكية... ⏳',
      generatingContent: 'نصنع لك محتوى ذكياً يستحق وقتك... 🎯',
      summary: 'الملخص',
      summaryNA: '⚠️ الفيديو قصير جداً أو لا يحتوي على محتوى كافٍ للتلخيص.',
      summaryTip: '💡',
      tipTitle: 'نصيحة:',
      tipDesc: 'للحصول على ملخص مفصل، ارفع فيديو:',
      tipPoint1: 'مدته دقيقة على الأقل',
      tipPoint2: 'يحتوي على محتوى تعليمي واضح',
      tipPoint3: 'بجودة صوت جيدة',
      keyPoints: 'الخريطة الذهنية',
      keyPointsNA: '📌 الخريطة الذهنية غير متاحة للفيديوهات القصيرة جداً.',
      description: 'الوصف',
      quiz: 'اختبار تفاعلي',
      quizCompleted: 'اكتمل الاختبار!',
      accuracy: 'الدقة',
      yourAnswer: 'إجابتك:',
      correctAnswer: 'الإجابة الصحيحة:',
      explanation: 'الشرح:',
      answerAll: 'يرجى الإجابة على جميع الأسئلة قبل التقديم.',
      submitAnswers: 'إرسال الإجابات',
      submitting: 'جاري الإرسال...',
      processingStatus: 'حالة المعالجة',
      completed: 'مكتمل ✅',
      processingLabel: 'قيد المعالجة... 🔄',
      failed: 'فشل ❌',
      pending: 'قيد الانتظار ⏳',
      retryAnalysis: 'إعادة التحليل',
      retrying: 'جاري الإعادة...',
      videoInfo: 'معلومات الفيديو',
      docInfo: 'معلومات المستند',
      categoryLabel: 'التصنيف',
      unspecified: 'غير محدد',
      duration: 'المدة',
      pageCount: 'عدد الصفحات',
      uploaded: 'تاريخ الرفع',
      aiModel: 'نموذج الذكاء الاصطناعي',
      notFound: 'الفيديو غير موجود',
      mindMap: 'خريطة المفاهيم البصرية',
      tapToFlip: 'اضغط لقلب البطاقة',
      flashcards: 'بطاقات المراجعة الذكية',
      exportPDF: 'تحميل PDF',
      studyMode: 'وضع المذاكرة',
      testMode: 'اختبار',
      pages: 'صفحة',
      mindMapTitle: 'الخريطة الذهنية التفاعلية',
    },
  },
};

export default useLanguageStore;
